/*
 * Copyright (C) 2017 Swift Navigation Inc.
 * Contact: Swift Navigation <dev@swiftnav.com>
 *
 * This source is subject to the license found in the file 'LICENSE' which must
 * be distributed together with this source. All other rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef GROUND_TRUTH_FILE_AND_FORMAT_H
#define GROUND_TRUTH_FILE_AND_FORMAT_H

#include <string>

namespace ground_truth {

// We support different CSV formats for truth data:
//  - UNKNOWN_CSV  : unspecified format
//  - STANDARD_CSV : standard Swift internal reference truth format
//  - ALTERNATE_CSV: custom truth format generated by an external customer
//                   (for more information see:
//                    https://swift-nav.atlassian.net/wiki/spaces/ENG/pages/1014726763)

enum TRUTH_LOG_FORMAT {
  UNKNOWN_CSV = 0,
  STANDARD_CSV,
  ALTERNATE_CSV,
};

struct TruthFileAndFormat {
  std::string file_path_;
  TRUTH_LOG_FORMAT log_format_;

  TruthFileAndFormat(const std::string &file_path,
                     const TRUTH_LOG_FORMAT log_format);
};

TRUTH_LOG_FORMAT string_to_truth_log_format(const std::string format_str);

}  // namespace ground_truth

#endif  // GROUND_TRUTH_FILE_AND_FORMAT_H
