/*
 * Copyright (C) 2011-2017 Swift Navigation Inc.
 * Author: Awesome Register Script Engine (ARSE)
 *
 * This source is subject to the license found in the file 'LICENSE' which must
 * be be distributed together with this source. All other rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 */

/* NT1065 Frontend v0.3.5 register map */

#ifndef NT1065_FRONTEND_H
#define NT1065_FRONTEND_H

#include <libswiftnav/common.h>

/* NT1065 Frontend register structure */
typedef struct {
  const volatile u32 STATUS;
  volatile u32 CONTROL;
  const volatile u32 VERSION;
  volatile u32 IRQS;
  volatile u32 RF1A_PINC;
  volatile u32 RF1B_PINC;
  volatile u32 RF2A_PINC;
  volatile u32 RF3A_PINC;
  volatile u32 RF4A_PINC;
  volatile u32 RF4B_PINC;
  volatile u32 RF1_NCO_RESET;
  volatile u32 RF2_NCO_RESET;
  volatile u32 RF3_NCO_RESET;
  volatile u32 RF4_NCO_RESET;
  volatile u32 DECIMATION0;
  volatile u32 DECIMATION1;
} nt1065_frontend_t;

/* Register: FE_STATUS */
#define FE_STATUS_CLOCK_MISSING_Pos (0U)
#define FE_STATUS_CLOCK_MISSING_Len (1U)
#define FE_STATUS_CLOCK_MISSING_Rst (0x0U)
#define FE_STATUS_CLOCK_MISSING_Msk (0x1U << FE_STATUS_CLOCK_MISSING_Pos)
#define GET_FE_STATUS_CLOCK_MISSING(REG) \
  (((REG)&FE_STATUS_CLOCK_MISSING_Msk) >> FE_STATUS_CLOCK_MISSING_Pos)

#define FE_STATUS_NUM_FRONTEND_CH_Pos (1U)
#define FE_STATUS_NUM_FRONTEND_CH_Len (4U)
#define FE_STATUS_NUM_FRONTEND_CH_Rst (0x0U)
#define FE_STATUS_NUM_FRONTEND_CH_Msk (0xFU << FE_STATUS_NUM_FRONTEND_CH_Pos)
#define GET_FE_STATUS_NUM_FRONTEND_CH(REG) \
  (((REG)&FE_STATUS_NUM_FRONTEND_CH_Msk) >> FE_STATUS_NUM_FRONTEND_CH_Pos)

#define FE_STATUS_TRK_DECIMATION_Pos (5U)
#define FE_STATUS_TRK_DECIMATION_Len (6U)
#define FE_STATUS_TRK_DECIMATION_Rst (0x4U)
#define FE_STATUS_TRK_DECIMATION_Msk (0x3FU << FE_STATUS_TRK_DECIMATION_Pos)
#define GET_FE_STATUS_TRK_DECIMATION(REG) \
  (((REG)&FE_STATUS_TRK_DECIMATION_Msk) >> FE_STATUS_TRK_DECIMATION_Pos)

/* Register: FE_CONTROL */
#define FE_CONTROL_VERSION_ADDR_Pos (0U)
#define FE_CONTROL_VERSION_ADDR_Len (4U)
#define FE_CONTROL_VERSION_ADDR_Rst (0x0U)
#define FE_CONTROL_VERSION_ADDR_Msk (0xFU << FE_CONTROL_VERSION_ADDR_Pos)
#define GET_FE_CONTROL_VERSION_ADDR(REG) \
  (((REG)&FE_CONTROL_VERSION_ADDR_Msk) >> FE_CONTROL_VERSION_ADDR_Pos)
#define SET_FE_CONTROL_VERSION_ADDR(REG, VAL) \
  (((REG) & ~FE_CONTROL_VERSION_ADDR_Msk) |   \
   ((VAL) << FE_CONTROL_VERSION_ADDR_Pos))

#define FE_CONTROL_ENABLE_RF1A_Pos (4U)
#define FE_CONTROL_ENABLE_RF1A_Len (1U)
#define FE_CONTROL_ENABLE_RF1A_Rst (0x0U)
#define FE_CONTROL_ENABLE_RF1A_Msk (0x1U << FE_CONTROL_ENABLE_RF1A_Pos)
#define GET_FE_CONTROL_ENABLE_RF1A(REG) \
  (((REG)&FE_CONTROL_ENABLE_RF1A_Msk) >> FE_CONTROL_ENABLE_RF1A_Pos)
#define SET_FE_CONTROL_ENABLE_RF1A(REG, VAL) \
  (((REG) & ~FE_CONTROL_ENABLE_RF1A_Msk) |   \
   ((VAL) << FE_CONTROL_ENABLE_RF1A_Pos))

#define FE_CONTROL_ENABLE_RF1B_Pos (5U)
#define FE_CONTROL_ENABLE_RF1B_Len (1U)
#define FE_CONTROL_ENABLE_RF1B_Rst (0x0U)
#define FE_CONTROL_ENABLE_RF1B_Msk (0x1U << FE_CONTROL_ENABLE_RF1B_Pos)
#define GET_FE_CONTROL_ENABLE_RF1B(REG) \
  (((REG)&FE_CONTROL_ENABLE_RF1B_Msk) >> FE_CONTROL_ENABLE_RF1B_Pos)
#define SET_FE_CONTROL_ENABLE_RF1B(REG, VAL) \
  (((REG) & ~FE_CONTROL_ENABLE_RF1B_Msk) |   \
   ((VAL) << FE_CONTROL_ENABLE_RF1B_Pos))

#define FE_CONTROL_ENABLE_RF2A_Pos (6U)
#define FE_CONTROL_ENABLE_RF2A_Len (1U)
#define FE_CONTROL_ENABLE_RF2A_Rst (0x0U)
#define FE_CONTROL_ENABLE_RF2A_Msk (0x1U << FE_CONTROL_ENABLE_RF2A_Pos)
#define GET_FE_CONTROL_ENABLE_RF2A(REG) \
  (((REG)&FE_CONTROL_ENABLE_RF2A_Msk) >> FE_CONTROL_ENABLE_RF2A_Pos)
#define SET_FE_CONTROL_ENABLE_RF2A(REG, VAL) \
  (((REG) & ~FE_CONTROL_ENABLE_RF2A_Msk) |   \
   ((VAL) << FE_CONTROL_ENABLE_RF2A_Pos))

#define FE_CONTROL_ENABLE_RF3A_Pos (7U)
#define FE_CONTROL_ENABLE_RF3A_Len (1U)
#define FE_CONTROL_ENABLE_RF3A_Rst (0x0U)
#define FE_CONTROL_ENABLE_RF3A_Msk (0x1U << FE_CONTROL_ENABLE_RF3A_Pos)
#define GET_FE_CONTROL_ENABLE_RF3A(REG) \
  (((REG)&FE_CONTROL_ENABLE_RF3A_Msk) >> FE_CONTROL_ENABLE_RF3A_Pos)
#define SET_FE_CONTROL_ENABLE_RF3A(REG, VAL) \
  (((REG) & ~FE_CONTROL_ENABLE_RF3A_Msk) |   \
   ((VAL) << FE_CONTROL_ENABLE_RF3A_Pos))

#define FE_CONTROL_ENABLE_RF4A_Pos (8U)
#define FE_CONTROL_ENABLE_RF4A_Len (1U)
#define FE_CONTROL_ENABLE_RF4A_Rst (0x0U)
#define FE_CONTROL_ENABLE_RF4A_Msk (0x1U << FE_CONTROL_ENABLE_RF4A_Pos)
#define GET_FE_CONTROL_ENABLE_RF4A(REG) \
  (((REG)&FE_CONTROL_ENABLE_RF4A_Msk) >> FE_CONTROL_ENABLE_RF4A_Pos)
#define SET_FE_CONTROL_ENABLE_RF4A(REG, VAL) \
  (((REG) & ~FE_CONTROL_ENABLE_RF4A_Msk) |   \
   ((VAL) << FE_CONTROL_ENABLE_RF4A_Pos))

#define FE_CONTROL_ENABLE_RF4B_Pos (9U)
#define FE_CONTROL_ENABLE_RF4B_Len (1U)
#define FE_CONTROL_ENABLE_RF4B_Rst (0x0U)
#define FE_CONTROL_ENABLE_RF4B_Msk (0x1U << FE_CONTROL_ENABLE_RF4B_Pos)
#define GET_FE_CONTROL_ENABLE_RF4B(REG) \
  (((REG)&FE_CONTROL_ENABLE_RF4B_Msk) >> FE_CONTROL_ENABLE_RF4B_Pos)
#define SET_FE_CONTROL_ENABLE_RF4B(REG, VAL) \
  (((REG) & ~FE_CONTROL_ENABLE_RF4B_Msk) |   \
   ((VAL) << FE_CONTROL_ENABLE_RF4B_Pos))

#define FE_CONTROL_RESET_RF1A_NCO_Pos (10U)
#define FE_CONTROL_RESET_RF1A_NCO_Len (1U)
#define FE_CONTROL_RESET_RF1A_NCO_Rst (0x0U)
#define FE_CONTROL_RESET_RF1A_NCO_Msk (0x1U << FE_CONTROL_RESET_RF1A_NCO_Pos)
#define GET_FE_CONTROL_RESET_RF1A_NCO(REG) \
  (((REG)&FE_CONTROL_RESET_RF1A_NCO_Msk) >> FE_CONTROL_RESET_RF1A_NCO_Pos)
#define SET_FE_CONTROL_RESET_RF1A_NCO(REG, VAL) \
  (((REG) & ~FE_CONTROL_RESET_RF1A_NCO_Msk) |   \
   ((VAL) << FE_CONTROL_RESET_RF1A_NCO_Pos))

#define FE_CONTROL_RESET_RF1B_NCO_Pos (11U)
#define FE_CONTROL_RESET_RF1B_NCO_Len (1U)
#define FE_CONTROL_RESET_RF1B_NCO_Rst (0x0U)
#define FE_CONTROL_RESET_RF1B_NCO_Msk (0x1U << FE_CONTROL_RESET_RF1B_NCO_Pos)
#define GET_FE_CONTROL_RESET_RF1B_NCO(REG) \
  (((REG)&FE_CONTROL_RESET_RF1B_NCO_Msk) >> FE_CONTROL_RESET_RF1B_NCO_Pos)
#define SET_FE_CONTROL_RESET_RF1B_NCO(REG, VAL) \
  (((REG) & ~FE_CONTROL_RESET_RF1B_NCO_Msk) |   \
   ((VAL) << FE_CONTROL_RESET_RF1B_NCO_Pos))

#define FE_CONTROL_RESET_RF2A_NCO_Pos (12U)
#define FE_CONTROL_RESET_RF2A_NCO_Len (1U)
#define FE_CONTROL_RESET_RF2A_NCO_Rst (0x0U)
#define FE_CONTROL_RESET_RF2A_NCO_Msk (0x1U << FE_CONTROL_RESET_RF2A_NCO_Pos)
#define GET_FE_CONTROL_RESET_RF2A_NCO(REG) \
  (((REG)&FE_CONTROL_RESET_RF2A_NCO_Msk) >> FE_CONTROL_RESET_RF2A_NCO_Pos)
#define SET_FE_CONTROL_RESET_RF2A_NCO(REG, VAL) \
  (((REG) & ~FE_CONTROL_RESET_RF2A_NCO_Msk) |   \
   ((VAL) << FE_CONTROL_RESET_RF2A_NCO_Pos))

#define FE_CONTROL_RESET_RF3A_NCO_Pos (13U)
#define FE_CONTROL_RESET_RF3A_NCO_Len (1U)
#define FE_CONTROL_RESET_RF3A_NCO_Rst (0x0U)
#define FE_CONTROL_RESET_RF3A_NCO_Msk (0x1U << FE_CONTROL_RESET_RF3A_NCO_Pos)
#define GET_FE_CONTROL_RESET_RF3A_NCO(REG) \
  (((REG)&FE_CONTROL_RESET_RF3A_NCO_Msk) >> FE_CONTROL_RESET_RF3A_NCO_Pos)
#define SET_FE_CONTROL_RESET_RF3A_NCO(REG, VAL) \
  (((REG) & ~FE_CONTROL_RESET_RF3A_NCO_Msk) |   \
   ((VAL) << FE_CONTROL_RESET_RF3A_NCO_Pos))

#define FE_CONTROL_RESET_RF4A_NCO_Pos (14U)
#define FE_CONTROL_RESET_RF4A_NCO_Len (1U)
#define FE_CONTROL_RESET_RF4A_NCO_Rst (0x0U)
#define FE_CONTROL_RESET_RF4A_NCO_Msk (0x1U << FE_CONTROL_RESET_RF4A_NCO_Pos)
#define GET_FE_CONTROL_RESET_RF4A_NCO(REG) \
  (((REG)&FE_CONTROL_RESET_RF4A_NCO_Msk) >> FE_CONTROL_RESET_RF4A_NCO_Pos)
#define SET_FE_CONTROL_RESET_RF4A_NCO(REG, VAL) \
  (((REG) & ~FE_CONTROL_RESET_RF4A_NCO_Msk) |   \
   ((VAL) << FE_CONTROL_RESET_RF4A_NCO_Pos))

#define FE_CONTROL_RESET_RF4B_NCO_Pos (15U)
#define FE_CONTROL_RESET_RF4B_NCO_Len (1U)
#define FE_CONTROL_RESET_RF4B_NCO_Rst (0x0U)
#define FE_CONTROL_RESET_RF4B_NCO_Msk (0x1U << FE_CONTROL_RESET_RF4B_NCO_Pos)
#define GET_FE_CONTROL_RESET_RF4B_NCO(REG) \
  (((REG)&FE_CONTROL_RESET_RF4B_NCO_Msk) >> FE_CONTROL_RESET_RF4B_NCO_Pos)
#define SET_FE_CONTROL_RESET_RF4B_NCO(REG, VAL) \
  (((REG) & ~FE_CONTROL_RESET_RF4B_NCO_Msk) |   \
   ((VAL) << FE_CONTROL_RESET_RF4B_NCO_Pos))

/* Register: FE_VERSION */
#define FE_VERSION_VALUE_Pos (0U)
#define FE_VERSION_VALUE_Len (32U)
#define FE_VERSION_VALUE_Rst (0x0U)
#define FE_VERSION_VALUE_Msk (0xFFFFFFFFU << FE_VERSION_VALUE_Pos)
#define GET_FE_VERSION_VALUE(REG) \
  (((REG)&FE_VERSION_VALUE_Msk) >> FE_VERSION_VALUE_Pos)

/* Register: FE_IRQS */
#define FE_IRQS_CLOCK_MISSING_Pos (0U)
#define FE_IRQS_CLOCK_MISSING_Len (1U)
#define FE_IRQS_CLOCK_MISSING_Rst (0x0U)
#define FE_IRQS_CLOCK_MISSING_Msk (0x1U << FE_IRQS_CLOCK_MISSING_Pos)
#define GET_FE_IRQS_CLOCK_MISSING(REG) \
  (((REG)&FE_IRQS_CLOCK_MISSING_Msk) >> FE_IRQS_CLOCK_MISSING_Pos)
#define SET_FE_IRQS_CLOCK_MISSING(REG, VAL) \
  (((REG) & ~FE_IRQS_CLOCK_MISSING_Msk) | ((VAL) << FE_IRQS_CLOCK_MISSING_Pos))

/* Register: FE_RF1A_PINC */
#define FE_RF1A_PINC_VALUE_Pos (0U)
#define FE_RF1A_PINC_VALUE_Len (32U)
#define FE_RF1A_PINC_VALUE_Rst (0x0U)
#define FE_RF1A_PINC_VALUE_Msk (0xFFFFFFFFU << FE_RF1A_PINC_VALUE_Pos)
#define GET_FE_RF1A_PINC_VALUE(REG) \
  (((REG)&FE_RF1A_PINC_VALUE_Msk) >> FE_RF1A_PINC_VALUE_Pos)
#define SET_FE_RF1A_PINC_VALUE(REG, VAL) \
  (((REG) & ~FE_RF1A_PINC_VALUE_Msk) | ((VAL) << FE_RF1A_PINC_VALUE_Pos))

/* Register: FE_RF1B_PINC */
#define FE_RF1B_PINC_VALUE_Pos (0U)
#define FE_RF1B_PINC_VALUE_Len (32U)
#define FE_RF1B_PINC_VALUE_Rst (0x0U)
#define FE_RF1B_PINC_VALUE_Msk (0xFFFFFFFFU << FE_RF1B_PINC_VALUE_Pos)
#define GET_FE_RF1B_PINC_VALUE(REG) \
  (((REG)&FE_RF1B_PINC_VALUE_Msk) >> FE_RF1B_PINC_VALUE_Pos)
#define SET_FE_RF1B_PINC_VALUE(REG, VAL) \
  (((REG) & ~FE_RF1B_PINC_VALUE_Msk) | ((VAL) << FE_RF1B_PINC_VALUE_Pos))

/* Register: FE_RF2A_PINC */
#define FE_RF2A_PINC_VALUE_Pos (0U)
#define FE_RF2A_PINC_VALUE_Len (32U)
#define FE_RF2A_PINC_VALUE_Rst (0x0U)
#define FE_RF2A_PINC_VALUE_Msk (0xFFFFFFFFU << FE_RF2A_PINC_VALUE_Pos)
#define GET_FE_RF2A_PINC_VALUE(REG) \
  (((REG)&FE_RF2A_PINC_VALUE_Msk) >> FE_RF2A_PINC_VALUE_Pos)
#define SET_FE_RF2A_PINC_VALUE(REG, VAL) \
  (((REG) & ~FE_RF2A_PINC_VALUE_Msk) | ((VAL) << FE_RF2A_PINC_VALUE_Pos))

/* Register: FE_RF3A_PINC */
#define FE_RF3A_PINC_VALUE_Pos (0U)
#define FE_RF3A_PINC_VALUE_Len (32U)
#define FE_RF3A_PINC_VALUE_Rst (0x0U)
#define FE_RF3A_PINC_VALUE_Msk (0xFFFFFFFFU << FE_RF3A_PINC_VALUE_Pos)
#define GET_FE_RF3A_PINC_VALUE(REG) \
  (((REG)&FE_RF3A_PINC_VALUE_Msk) >> FE_RF3A_PINC_VALUE_Pos)
#define SET_FE_RF3A_PINC_VALUE(REG, VAL) \
  (((REG) & ~FE_RF3A_PINC_VALUE_Msk) | ((VAL) << FE_RF3A_PINC_VALUE_Pos))

/* Register: FE_RF4A_PINC */
#define FE_RF4A_PINC_VALUE_Pos (0U)
#define FE_RF4A_PINC_VALUE_Len (32U)
#define FE_RF4A_PINC_VALUE_Rst (0x0U)
#define FE_RF4A_PINC_VALUE_Msk (0xFFFFFFFFU << FE_RF4A_PINC_VALUE_Pos)
#define GET_FE_RF4A_PINC_VALUE(REG) \
  (((REG)&FE_RF4A_PINC_VALUE_Msk) >> FE_RF4A_PINC_VALUE_Pos)
#define SET_FE_RF4A_PINC_VALUE(REG, VAL) \
  (((REG) & ~FE_RF4A_PINC_VALUE_Msk) | ((VAL) << FE_RF4A_PINC_VALUE_Pos))

/* Register: FE_RF4B_PINC */
#define FE_RF4B_PINC_VALUE_Pos (0U)
#define FE_RF4B_PINC_VALUE_Len (32U)
#define FE_RF4B_PINC_VALUE_Rst (0x0U)
#define FE_RF4B_PINC_VALUE_Msk (0xFFFFFFFFU << FE_RF4B_PINC_VALUE_Pos)
#define GET_FE_RF4B_PINC_VALUE(REG) \
  (((REG)&FE_RF4B_PINC_VALUE_Msk) >> FE_RF4B_PINC_VALUE_Pos)
#define SET_FE_RF4B_PINC_VALUE(REG, VAL) \
  (((REG) & ~FE_RF4B_PINC_VALUE_Msk) | ((VAL) << FE_RF4B_PINC_VALUE_Pos))

/* Register: FE_RF1_NCO_RESET */
#define FE_RF1_NCO_RESET_RF1A_Pos (0U)
#define FE_RF1_NCO_RESET_RF1A_Len (16U)
#define FE_RF1_NCO_RESET_RF1A_Rst (0xFFFFU)
#define FE_RF1_NCO_RESET_RF1A_Msk (0xFFFFU << FE_RF1_NCO_RESET_RF1A_Pos)
#define GET_FE_RF1_NCO_RESET_RF1A(REG) \
  (((REG)&FE_RF1_NCO_RESET_RF1A_Msk) >> FE_RF1_NCO_RESET_RF1A_Pos)
#define SET_FE_RF1_NCO_RESET_RF1A(REG, VAL) \
  (((REG) & ~FE_RF1_NCO_RESET_RF1A_Msk) | ((VAL) << FE_RF1_NCO_RESET_RF1A_Pos))

#define FE_RF1_NCO_RESET_RF1B_Pos (16U)
#define FE_RF1_NCO_RESET_RF1B_Len (16U)
#define FE_RF1_NCO_RESET_RF1B_Rst (0xFFFFU)
#define FE_RF1_NCO_RESET_RF1B_Msk (0xFFFFU << FE_RF1_NCO_RESET_RF1B_Pos)
#define GET_FE_RF1_NCO_RESET_RF1B(REG) \
  (((REG)&FE_RF1_NCO_RESET_RF1B_Msk) >> FE_RF1_NCO_RESET_RF1B_Pos)
#define SET_FE_RF1_NCO_RESET_RF1B(REG, VAL) \
  (((REG) & ~FE_RF1_NCO_RESET_RF1B_Msk) | ((VAL) << FE_RF1_NCO_RESET_RF1B_Pos))

/* Register: FE_RF2_NCO_RESET */
#define FE_RF2_NCO_RESET_RF2A_Pos (0U)
#define FE_RF2_NCO_RESET_RF2A_Len (16U)
#define FE_RF2_NCO_RESET_RF2A_Rst (0xFFFFU)
#define FE_RF2_NCO_RESET_RF2A_Msk (0xFFFFU << FE_RF2_NCO_RESET_RF2A_Pos)
#define GET_FE_RF2_NCO_RESET_RF2A(REG) \
  (((REG)&FE_RF2_NCO_RESET_RF2A_Msk) >> FE_RF2_NCO_RESET_RF2A_Pos)
#define SET_FE_RF2_NCO_RESET_RF2A(REG, VAL) \
  (((REG) & ~FE_RF2_NCO_RESET_RF2A_Msk) | ((VAL) << FE_RF2_NCO_RESET_RF2A_Pos))

/* Register: FE_RF3_NCO_RESET */
#define FE_RF3_NCO_RESET_RF3A_Pos (0U)
#define FE_RF3_NCO_RESET_RF3A_Len (16U)
#define FE_RF3_NCO_RESET_RF3A_Rst (0xFFFFU)
#define FE_RF3_NCO_RESET_RF3A_Msk (0xFFFFU << FE_RF3_NCO_RESET_RF3A_Pos)
#define GET_FE_RF3_NCO_RESET_RF3A(REG) \
  (((REG)&FE_RF3_NCO_RESET_RF3A_Msk) >> FE_RF3_NCO_RESET_RF3A_Pos)
#define SET_FE_RF3_NCO_RESET_RF3A(REG, VAL) \
  (((REG) & ~FE_RF3_NCO_RESET_RF3A_Msk) | ((VAL) << FE_RF3_NCO_RESET_RF3A_Pos))

/* Register: FE_RF4_NCO_RESET */
#define FE_RF4_NCO_RESET_RF4A_Pos (0U)
#define FE_RF4_NCO_RESET_RF4A_Len (16U)
#define FE_RF4_NCO_RESET_RF4A_Rst (0xFFFFU)
#define FE_RF4_NCO_RESET_RF4A_Msk (0xFFFFU << FE_RF4_NCO_RESET_RF4A_Pos)
#define GET_FE_RF4_NCO_RESET_RF4A(REG) \
  (((REG)&FE_RF4_NCO_RESET_RF4A_Msk) >> FE_RF4_NCO_RESET_RF4A_Pos)
#define SET_FE_RF4_NCO_RESET_RF4A(REG, VAL) \
  (((REG) & ~FE_RF4_NCO_RESET_RF4A_Msk) | ((VAL) << FE_RF4_NCO_RESET_RF4A_Pos))

#define FE_RF4_NCO_RESET_RF4B_Pos (16U)
#define FE_RF4_NCO_RESET_RF4B_Len (16U)
#define FE_RF4_NCO_RESET_RF4B_Rst (0xFFFFU)
#define FE_RF4_NCO_RESET_RF4B_Msk (0xFFFFU << FE_RF4_NCO_RESET_RF4B_Pos)
#define GET_FE_RF4_NCO_RESET_RF4B(REG) \
  (((REG)&FE_RF4_NCO_RESET_RF4B_Msk) >> FE_RF4_NCO_RESET_RF4B_Pos)
#define SET_FE_RF4_NCO_RESET_RF4B(REG, VAL) \
  (((REG) & ~FE_RF4_NCO_RESET_RF4B_Msk) | ((VAL) << FE_RF4_NCO_RESET_RF4B_Pos))

/* Register: FE_DECIMATION0 */
#define FE_DECIMATION0_RF1A_Pos (0U)
#define FE_DECIMATION0_RF1A_Len (6U)
#define FE_DECIMATION0_RF1A_Rst (0x4U)
#define FE_DECIMATION0_RF1A_Msk (0x3FU << FE_DECIMATION0_RF1A_Pos)
#define GET_FE_DECIMATION0_RF1A(REG) \
  (((REG)&FE_DECIMATION0_RF1A_Msk) >> FE_DECIMATION0_RF1A_Pos)
#define SET_FE_DECIMATION0_RF1A(REG, VAL) \
  (((REG) & ~FE_DECIMATION0_RF1A_Msk) | ((VAL) << FE_DECIMATION0_RF1A_Pos))

#define FE_DECIMATION0_RF1B_Pos (8U)
#define FE_DECIMATION0_RF1B_Len (6U)
#define FE_DECIMATION0_RF1B_Rst (0x4U)
#define FE_DECIMATION0_RF1B_Msk (0x3FU << FE_DECIMATION0_RF1B_Pos)
#define GET_FE_DECIMATION0_RF1B(REG) \
  (((REG)&FE_DECIMATION0_RF1B_Msk) >> FE_DECIMATION0_RF1B_Pos)
#define SET_FE_DECIMATION0_RF1B(REG, VAL) \
  (((REG) & ~FE_DECIMATION0_RF1B_Msk) | ((VAL) << FE_DECIMATION0_RF1B_Pos))

#define FE_DECIMATION0_RF2A_Pos (16U)
#define FE_DECIMATION0_RF2A_Len (6U)
#define FE_DECIMATION0_RF2A_Rst (0x4U)
#define FE_DECIMATION0_RF2A_Msk (0x3FU << FE_DECIMATION0_RF2A_Pos)
#define GET_FE_DECIMATION0_RF2A(REG) \
  (((REG)&FE_DECIMATION0_RF2A_Msk) >> FE_DECIMATION0_RF2A_Pos)
#define SET_FE_DECIMATION0_RF2A(REG, VAL) \
  (((REG) & ~FE_DECIMATION0_RF2A_Msk) | ((VAL) << FE_DECIMATION0_RF2A_Pos))

#define FE_DECIMATION0_RF3A_Pos (24U)
#define FE_DECIMATION0_RF3A_Len (6U)
#define FE_DECIMATION0_RF3A_Rst (0x4U)
#define FE_DECIMATION0_RF3A_Msk (0x3FU << FE_DECIMATION0_RF3A_Pos)
#define GET_FE_DECIMATION0_RF3A(REG) \
  (((REG)&FE_DECIMATION0_RF3A_Msk) >> FE_DECIMATION0_RF3A_Pos)
#define SET_FE_DECIMATION0_RF3A(REG, VAL) \
  (((REG) & ~FE_DECIMATION0_RF3A_Msk) | ((VAL) << FE_DECIMATION0_RF3A_Pos))

/* Register: FE_DECIMATION1 */
#define FE_DECIMATION1_RF4A_Pos (0U)
#define FE_DECIMATION1_RF4A_Len (6U)
#define FE_DECIMATION1_RF4A_Rst (0x4U)
#define FE_DECIMATION1_RF4A_Msk (0x3FU << FE_DECIMATION1_RF4A_Pos)
#define GET_FE_DECIMATION1_RF4A(REG) \
  (((REG)&FE_DECIMATION1_RF4A_Msk) >> FE_DECIMATION1_RF4A_Pos)
#define SET_FE_DECIMATION1_RF4A(REG, VAL) \
  (((REG) & ~FE_DECIMATION1_RF4A_Msk) | ((VAL) << FE_DECIMATION1_RF4A_Pos))

#define FE_DECIMATION1_RF4B_Pos (8U)
#define FE_DECIMATION1_RF4B_Len (6U)
#define FE_DECIMATION1_RF4B_Rst (0x4U)
#define FE_DECIMATION1_RF4B_Msk (0x3FU << FE_DECIMATION1_RF4B_Pos)
#define GET_FE_DECIMATION1_RF4B(REG) \
  (((REG)&FE_DECIMATION1_RF4B_Msk) >> FE_DECIMATION1_RF4B_Pos)
#define SET_FE_DECIMATION1_RF4B(REG, VAL) \
  (((REG) & ~FE_DECIMATION1_RF4B_Msk) | ((VAL) << FE_DECIMATION1_RF4B_Pos))

#endif
