/*
 * Copyright (C) 2011-2017 Swift Navigation Inc.
 * Author: Awesome Register Script Engine (ARSE)
 *
 * This source is subject to the license found in the file 'LICENSE' which must
 * be be distributed together with this source. All other rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 */

/* NT1065 Frontend v0.3.1 register map */

#ifndef NT1065_FRONTEND_H
#define NT1065_FRONTEND_H

#include <libswiftnav/common.h>

/* NT1065 Frontend register structure */
typedef struct {
  const volatile u32 STATUS;
        volatile u32 CONTROL;
  const volatile u32 VERSION;
        volatile u32 IRQS;
        volatile u32 RF1_PINC;
        volatile u32 RF2_PINC;
        volatile u32 RF3_PINC;
        volatile u32 RF4_PINC;
        volatile u32 NCO_RESET0;
        volatile u32 NCO_RESET1;
} nt1065_frontend_t;

/* Register: FE_STATUS */
#define FE_STATUS_CLOCK_MISSING_Pos (0U)
#define FE_STATUS_CLOCK_MISSING_Len (1U)
#define FE_STATUS_CLOCK_MISSING_Rst (0x0U)
#define FE_STATUS_CLOCK_MISSING_Msk \
    (0x1U << FE_STATUS_CLOCK_MISSING_Pos)
#define GET_FE_STATUS_CLOCK_MISSING(REG) \
    (((REG) & FE_STATUS_CLOCK_MISSING_Msk) >> FE_STATUS_CLOCK_MISSING_Pos)

#define FE_STATUS_NUM_FRONTEND_CH_Pos (1U)
#define FE_STATUS_NUM_FRONTEND_CH_Len (4U)
#define FE_STATUS_NUM_FRONTEND_CH_Rst (0x0U)
#define FE_STATUS_NUM_FRONTEND_CH_Msk \
    (0xFU << FE_STATUS_NUM_FRONTEND_CH_Pos)
#define GET_FE_STATUS_NUM_FRONTEND_CH(REG) \
    (((REG) & FE_STATUS_NUM_FRONTEND_CH_Msk) >> FE_STATUS_NUM_FRONTEND_CH_Pos)

#define FE_STATUS_TRK_DECIMATION_Pos (5U)
#define FE_STATUS_TRK_DECIMATION_Len (6U)
#define FE_STATUS_TRK_DECIMATION_Rst (0x4U)
#define FE_STATUS_TRK_DECIMATION_Msk \
    (0x3FU << FE_STATUS_TRK_DECIMATION_Pos)
#define GET_FE_STATUS_TRK_DECIMATION(REG) \
    (((REG) & FE_STATUS_TRK_DECIMATION_Msk) >> FE_STATUS_TRK_DECIMATION_Pos)

/* Register: FE_CONTROL */
#define FE_CONTROL_VERSION_ADDR_Pos (0U)
#define FE_CONTROL_VERSION_ADDR_Len (4U)
#define FE_CONTROL_VERSION_ADDR_Rst (0x0U)
#define FE_CONTROL_VERSION_ADDR_Msk \
    (0xFU << FE_CONTROL_VERSION_ADDR_Pos)
#define GET_FE_CONTROL_VERSION_ADDR(REG) \
    (((REG) & FE_CONTROL_VERSION_ADDR_Msk) >> FE_CONTROL_VERSION_ADDR_Pos)
#define SET_FE_CONTROL_VERSION_ADDR(REG, VAL) \
    (((REG) & ~FE_CONTROL_VERSION_ADDR_Msk) | ((VAL) << FE_CONTROL_VERSION_ADDR_Pos))

#define FE_CONTROL_ENABLE_RF1_Pos (4U)
#define FE_CONTROL_ENABLE_RF1_Len (1U)
#define FE_CONTROL_ENABLE_RF1_Rst (0x0U)
#define FE_CONTROL_ENABLE_RF1_Msk \
    (0x1U << FE_CONTROL_ENABLE_RF1_Pos)
#define GET_FE_CONTROL_ENABLE_RF1(REG) \
    (((REG) & FE_CONTROL_ENABLE_RF1_Msk) >> FE_CONTROL_ENABLE_RF1_Pos)
#define SET_FE_CONTROL_ENABLE_RF1(REG, VAL) \
    (((REG) & ~FE_CONTROL_ENABLE_RF1_Msk) | ((VAL) << FE_CONTROL_ENABLE_RF1_Pos))

#define FE_CONTROL_ENABLE_RF2_Pos (5U)
#define FE_CONTROL_ENABLE_RF2_Len (1U)
#define FE_CONTROL_ENABLE_RF2_Rst (0x0U)
#define FE_CONTROL_ENABLE_RF2_Msk \
    (0x1U << FE_CONTROL_ENABLE_RF2_Pos)
#define GET_FE_CONTROL_ENABLE_RF2(REG) \
    (((REG) & FE_CONTROL_ENABLE_RF2_Msk) >> FE_CONTROL_ENABLE_RF2_Pos)
#define SET_FE_CONTROL_ENABLE_RF2(REG, VAL) \
    (((REG) & ~FE_CONTROL_ENABLE_RF2_Msk) | ((VAL) << FE_CONTROL_ENABLE_RF2_Pos))

#define FE_CONTROL_ENABLE_RF3_Pos (6U)
#define FE_CONTROL_ENABLE_RF3_Len (1U)
#define FE_CONTROL_ENABLE_RF3_Rst (0x0U)
#define FE_CONTROL_ENABLE_RF3_Msk \
    (0x1U << FE_CONTROL_ENABLE_RF3_Pos)
#define GET_FE_CONTROL_ENABLE_RF3(REG) \
    (((REG) & FE_CONTROL_ENABLE_RF3_Msk) >> FE_CONTROL_ENABLE_RF3_Pos)
#define SET_FE_CONTROL_ENABLE_RF3(REG, VAL) \
    (((REG) & ~FE_CONTROL_ENABLE_RF3_Msk) | ((VAL) << FE_CONTROL_ENABLE_RF3_Pos))

#define FE_CONTROL_ENABLE_RF4_Pos (7U)
#define FE_CONTROL_ENABLE_RF4_Len (1U)
#define FE_CONTROL_ENABLE_RF4_Rst (0x0U)
#define FE_CONTROL_ENABLE_RF4_Msk \
    (0x1U << FE_CONTROL_ENABLE_RF4_Pos)
#define GET_FE_CONTROL_ENABLE_RF4(REG) \
    (((REG) & FE_CONTROL_ENABLE_RF4_Msk) >> FE_CONTROL_ENABLE_RF4_Pos)
#define SET_FE_CONTROL_ENABLE_RF4(REG, VAL) \
    (((REG) & ~FE_CONTROL_ENABLE_RF4_Msk) | ((VAL) << FE_CONTROL_ENABLE_RF4_Pos))

#define FE_CONTROL_RESET_RF1_NCO_Pos (8U)
#define FE_CONTROL_RESET_RF1_NCO_Len (1U)
#define FE_CONTROL_RESET_RF1_NCO_Rst (0x0U)
#define FE_CONTROL_RESET_RF1_NCO_Msk \
    (0x1U << FE_CONTROL_RESET_RF1_NCO_Pos)
#define GET_FE_CONTROL_RESET_RF1_NCO(REG) \
    (((REG) & FE_CONTROL_RESET_RF1_NCO_Msk) >> FE_CONTROL_RESET_RF1_NCO_Pos)
#define SET_FE_CONTROL_RESET_RF1_NCO(REG, VAL) \
    (((REG) & ~FE_CONTROL_RESET_RF1_NCO_Msk) | ((VAL) << FE_CONTROL_RESET_RF1_NCO_Pos))

#define FE_CONTROL_RESET_RF2_NCO_Pos (9U)
#define FE_CONTROL_RESET_RF2_NCO_Len (1U)
#define FE_CONTROL_RESET_RF2_NCO_Rst (0x0U)
#define FE_CONTROL_RESET_RF2_NCO_Msk \
    (0x1U << FE_CONTROL_RESET_RF2_NCO_Pos)
#define GET_FE_CONTROL_RESET_RF2_NCO(REG) \
    (((REG) & FE_CONTROL_RESET_RF2_NCO_Msk) >> FE_CONTROL_RESET_RF2_NCO_Pos)
#define SET_FE_CONTROL_RESET_RF2_NCO(REG, VAL) \
    (((REG) & ~FE_CONTROL_RESET_RF2_NCO_Msk) | ((VAL) << FE_CONTROL_RESET_RF2_NCO_Pos))

#define FE_CONTROL_RESET_RF3_NCO_Pos (10U)
#define FE_CONTROL_RESET_RF3_NCO_Len (1U)
#define FE_CONTROL_RESET_RF3_NCO_Rst (0x0U)
#define FE_CONTROL_RESET_RF3_NCO_Msk \
    (0x1U << FE_CONTROL_RESET_RF3_NCO_Pos)
#define GET_FE_CONTROL_RESET_RF3_NCO(REG) \
    (((REG) & FE_CONTROL_RESET_RF3_NCO_Msk) >> FE_CONTROL_RESET_RF3_NCO_Pos)
#define SET_FE_CONTROL_RESET_RF3_NCO(REG, VAL) \
    (((REG) & ~FE_CONTROL_RESET_RF3_NCO_Msk) | ((VAL) << FE_CONTROL_RESET_RF3_NCO_Pos))

#define FE_CONTROL_RESET_RF4_NCO_Pos (11U)
#define FE_CONTROL_RESET_RF4_NCO_Len (1U)
#define FE_CONTROL_RESET_RF4_NCO_Rst (0x0U)
#define FE_CONTROL_RESET_RF4_NCO_Msk \
    (0x1U << FE_CONTROL_RESET_RF4_NCO_Pos)
#define GET_FE_CONTROL_RESET_RF4_NCO(REG) \
    (((REG) & FE_CONTROL_RESET_RF4_NCO_Msk) >> FE_CONTROL_RESET_RF4_NCO_Pos)
#define SET_FE_CONTROL_RESET_RF4_NCO(REG, VAL) \
    (((REG) & ~FE_CONTROL_RESET_RF4_NCO_Msk) | ((VAL) << FE_CONTROL_RESET_RF4_NCO_Pos))

/* Register: FE_VERSION */
#define FE_VERSION_VALUE_Pos (0U)
#define FE_VERSION_VALUE_Len (32U)
#define FE_VERSION_VALUE_Rst (0x0U)
#define FE_VERSION_VALUE_Msk \
    (0xFFFFFFFFU << FE_VERSION_VALUE_Pos)
#define GET_FE_VERSION_VALUE(REG) \
    (((REG) & FE_VERSION_VALUE_Msk) >> FE_VERSION_VALUE_Pos)

/* Register: FE_IRQS */
#define FE_IRQS_CLOCK_MISSING_Pos (0U)
#define FE_IRQS_CLOCK_MISSING_Len (1U)
#define FE_IRQS_CLOCK_MISSING_Rst (0x0U)
#define FE_IRQS_CLOCK_MISSING_Msk \
    (0x1U << FE_IRQS_CLOCK_MISSING_Pos)
#define GET_FE_IRQS_CLOCK_MISSING(REG) \
    (((REG) & FE_IRQS_CLOCK_MISSING_Msk) >> FE_IRQS_CLOCK_MISSING_Pos)
#define SET_FE_IRQS_CLOCK_MISSING(REG, VAL) \
    (((REG) & ~FE_IRQS_CLOCK_MISSING_Msk) | ((VAL) << FE_IRQS_CLOCK_MISSING_Pos))

/* Register: FE_RF1_PINC */
#define FE_RF1_PINC_VALUE_Pos (0U)
#define FE_RF1_PINC_VALUE_Len (32U)
#define FE_RF1_PINC_VALUE_Rst (0x0U)
#define FE_RF1_PINC_VALUE_Msk \
    (0xFFFFFFFFU << FE_RF1_PINC_VALUE_Pos)
#define GET_FE_RF1_PINC_VALUE(REG) \
    (((REG) & FE_RF1_PINC_VALUE_Msk) >> FE_RF1_PINC_VALUE_Pos)
#define SET_FE_RF1_PINC_VALUE(REG, VAL) \
    (((REG) & ~FE_RF1_PINC_VALUE_Msk) | ((VAL) << FE_RF1_PINC_VALUE_Pos))

/* Register: FE_RF2_PINC */
#define FE_RF2_PINC_VALUE_Pos (0U)
#define FE_RF2_PINC_VALUE_Len (32U)
#define FE_RF2_PINC_VALUE_Rst (0x0U)
#define FE_RF2_PINC_VALUE_Msk \
    (0xFFFFFFFFU << FE_RF2_PINC_VALUE_Pos)
#define GET_FE_RF2_PINC_VALUE(REG) \
    (((REG) & FE_RF2_PINC_VALUE_Msk) >> FE_RF2_PINC_VALUE_Pos)
#define SET_FE_RF2_PINC_VALUE(REG, VAL) \
    (((REG) & ~FE_RF2_PINC_VALUE_Msk) | ((VAL) << FE_RF2_PINC_VALUE_Pos))

/* Register: FE_RF3_PINC */
#define FE_RF3_PINC_VALUE_Pos (0U)
#define FE_RF3_PINC_VALUE_Len (32U)
#define FE_RF3_PINC_VALUE_Rst (0x0U)
#define FE_RF3_PINC_VALUE_Msk \
    (0xFFFFFFFFU << FE_RF3_PINC_VALUE_Pos)
#define GET_FE_RF3_PINC_VALUE(REG) \
    (((REG) & FE_RF3_PINC_VALUE_Msk) >> FE_RF3_PINC_VALUE_Pos)
#define SET_FE_RF3_PINC_VALUE(REG, VAL) \
    (((REG) & ~FE_RF3_PINC_VALUE_Msk) | ((VAL) << FE_RF3_PINC_VALUE_Pos))

/* Register: FE_RF4_PINC */
#define FE_RF4_PINC_VALUE_Pos (0U)
#define FE_RF4_PINC_VALUE_Len (32U)
#define FE_RF4_PINC_VALUE_Rst (0x0U)
#define FE_RF4_PINC_VALUE_Msk \
    (0xFFFFFFFFU << FE_RF4_PINC_VALUE_Pos)
#define GET_FE_RF4_PINC_VALUE(REG) \
    (((REG) & FE_RF4_PINC_VALUE_Msk) >> FE_RF4_PINC_VALUE_Pos)
#define SET_FE_RF4_PINC_VALUE(REG, VAL) \
    (((REG) & ~FE_RF4_PINC_VALUE_Msk) | ((VAL) << FE_RF4_PINC_VALUE_Pos))

/* Register: FE_NCO_RESET0 */
#define FE_NCO_RESET0_RF1_Pos (0U)
#define FE_NCO_RESET0_RF1_Len (16U)
#define FE_NCO_RESET0_RF1_Rst (0xFFFFU)
#define FE_NCO_RESET0_RF1_Msk \
    (0xFFFFU << FE_NCO_RESET0_RF1_Pos)
#define GET_FE_NCO_RESET0_RF1(REG) \
    (((REG) & FE_NCO_RESET0_RF1_Msk) >> FE_NCO_RESET0_RF1_Pos)
#define SET_FE_NCO_RESET0_RF1(REG, VAL) \
    (((REG) & ~FE_NCO_RESET0_RF1_Msk) | ((VAL) << FE_NCO_RESET0_RF1_Pos))

#define FE_NCO_RESET0_RF2_Pos (16U)
#define FE_NCO_RESET0_RF2_Len (16U)
#define FE_NCO_RESET0_RF2_Rst (0xFFFFU)
#define FE_NCO_RESET0_RF2_Msk \
    (0xFFFFU << FE_NCO_RESET0_RF2_Pos)
#define GET_FE_NCO_RESET0_RF2(REG) \
    (((REG) & FE_NCO_RESET0_RF2_Msk) >> FE_NCO_RESET0_RF2_Pos)
#define SET_FE_NCO_RESET0_RF2(REG, VAL) \
    (((REG) & ~FE_NCO_RESET0_RF2_Msk) | ((VAL) << FE_NCO_RESET0_RF2_Pos))

/* Register: FE_NCO_RESET1 */
#define FE_NCO_RESET1_RF3_Pos (0U)
#define FE_NCO_RESET1_RF3_Len (16U)
#define FE_NCO_RESET1_RF3_Rst (0xFFFFU)
#define FE_NCO_RESET1_RF3_Msk \
    (0xFFFFU << FE_NCO_RESET1_RF3_Pos)
#define GET_FE_NCO_RESET1_RF3(REG) \
    (((REG) & FE_NCO_RESET1_RF3_Msk) >> FE_NCO_RESET1_RF3_Pos)
#define SET_FE_NCO_RESET1_RF3(REG, VAL) \
    (((REG) & ~FE_NCO_RESET1_RF3_Msk) | ((VAL) << FE_NCO_RESET1_RF3_Pos))

#define FE_NCO_RESET1_RF4_Pos (16U)
#define FE_NCO_RESET1_RF4_Len (16U)
#define FE_NCO_RESET1_RF4_Rst (0xFFFFU)
#define FE_NCO_RESET1_RF4_Msk \
    (0xFFFFU << FE_NCO_RESET1_RF4_Pos)
#define GET_FE_NCO_RESET1_RF4(REG) \
    (((REG) & FE_NCO_RESET1_RF4_Msk) >> FE_NCO_RESET1_RF4_Pos)
#define SET_FE_NCO_RESET1_RF4(REG, VAL) \
    (((REG) & ~FE_NCO_RESET1_RF4_Msk) | ((VAL) << FE_NCO_RESET1_RF4_Pos))

#endif
