/*
 * Copyright (C) 2011-2017 Swift Navigation Inc.
 * Author: Awesome Register Script Engine (ARSE)
 *
 * This source is subject to the license found in the file 'LICENSE' which must
 * be be distributed together with this source. All other rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 */

/* NT1065 Frontend v0.3.7 register map */

#ifndef NT1065_FRONTEND_H
#define NT1065_FRONTEND_H

#include <libswiftnav/common.h>

/* Version */
#define FE_VERSION (0x00030007)

/* NT1065 Frontend register structure */
typedef struct { const volatile u32 STATUS; } nt1065_frontend_t;

/* Register: FE_STATUS */
#define FE_STATUS_RF1A_GAIN_Pos (0U)
#define FE_STATUS_RF1A_GAIN_Len (5U)
#define FE_STATUS_RF1A_GAIN_Rst (0x4U)
#define FE_STATUS_RF1A_GAIN_Msk (0x1FU << FE_STATUS_RF1A_GAIN_Pos)
#define GET_FE_STATUS_RF1A_GAIN(REG) \
  (((REG)&FE_STATUS_RF1A_GAIN_Msk) >> FE_STATUS_RF1A_GAIN_Pos)

#define FE_STATUS_RF1B_GAIN_Pos (5U)
#define FE_STATUS_RF1B_GAIN_Len (5U)
#define FE_STATUS_RF1B_GAIN_Rst (0x4U)
#define FE_STATUS_RF1B_GAIN_Msk (0x1FU << FE_STATUS_RF1B_GAIN_Pos)
#define GET_FE_STATUS_RF1B_GAIN(REG) \
  (((REG)&FE_STATUS_RF1B_GAIN_Msk) >> FE_STATUS_RF1B_GAIN_Pos)

#define FE_STATUS_RF2A_GAIN_Pos (10U)
#define FE_STATUS_RF2A_GAIN_Len (5U)
#define FE_STATUS_RF2A_GAIN_Rst (0x4U)
#define FE_STATUS_RF2A_GAIN_Msk (0x1FU << FE_STATUS_RF2A_GAIN_Pos)
#define GET_FE_STATUS_RF2A_GAIN(REG) \
  (((REG)&FE_STATUS_RF2A_GAIN_Msk) >> FE_STATUS_RF2A_GAIN_Pos)

#define FE_STATUS_RF3A_GAIN_Pos (15U)
#define FE_STATUS_RF3A_GAIN_Len (5U)
#define FE_STATUS_RF3A_GAIN_Rst (0x4U)
#define FE_STATUS_RF3A_GAIN_Msk (0x1FU << FE_STATUS_RF3A_GAIN_Pos)
#define GET_FE_STATUS_RF3A_GAIN(REG) \
  (((REG)&FE_STATUS_RF3A_GAIN_Msk) >> FE_STATUS_RF3A_GAIN_Pos)

#define FE_STATUS_RF4A_GAIN_Pos (20U)
#define FE_STATUS_RF4A_GAIN_Len (5U)
#define FE_STATUS_RF4A_GAIN_Rst (0x4U)
#define FE_STATUS_RF4A_GAIN_Msk (0x1FU << FE_STATUS_RF4A_GAIN_Pos)
#define GET_FE_STATUS_RF4A_GAIN(REG) \
  (((REG)&FE_STATUS_RF4A_GAIN_Msk) >> FE_STATUS_RF4A_GAIN_Pos)

#define FE_STATUS_RF4B_GAIN_Pos (25U)
#define FE_STATUS_RF4B_GAIN_Len (5U)
#define FE_STATUS_RF4B_GAIN_Rst (0x4U)
#define FE_STATUS_RF4B_GAIN_Msk (0x1FU << FE_STATUS_RF4B_GAIN_Pos)
#define GET_FE_STATUS_RF4B_GAIN(REG) \
  (((REG)&FE_STATUS_RF4B_GAIN_Msk) >> FE_STATUS_RF4B_GAIN_Pos)

#define FE_STATUS_CLOCK_MISSING_Pos (31U)
#define FE_STATUS_CLOCK_MISSING_Len (1U)
#define FE_STATUS_CLOCK_MISSING_Rst (0x0U)
#define FE_STATUS_CLOCK_MISSING_Msk (0x1U << FE_STATUS_CLOCK_MISSING_Pos)
#define GET_FE_STATUS_CLOCK_MISSING(REG) \
  (((REG)&FE_STATUS_CLOCK_MISSING_Msk) >> FE_STATUS_CLOCK_MISSING_Pos)

#endif
