dist: trusty
sudo: required

language: c
notifications:
  slack:
    rooms:
      - snav:JdxlaluulRxggMfKcNFhurbc#firmware
    on_pull_requests: false
    on_failure: never
    on_success: never

branches:
  only:
    - v1.6.0-release
    - master
    - /^v\d+\.\d+\.0-release$/
    - v2.1-dev-branch

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - C_COMPILER=gcc-5 CXX_COMPILER=g++-5
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-format-4.0
      env: TESTENV=lint
    - os: osx
      osx_image: xcode8
      env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5

before_install:
  - ./scripts/ci/check_for_s3_cred.sh || travis_terminate 1
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc5 --enable-cxx; fi
  - pip install --user --upgrade awscli
  - git fetch --tags --unshallow

install:
  # If it's a cron build, pull libswiftnav-private master; otherwise
  # use the committed version.  Travis doesn't have a good way to set
  # a special variable just for this case, so we have to gate only on
  # the event type.
  - if [[ "$TESTENV" == "lint" ]]; then
      echo "lint";
    elif [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
      ANSIBLE_SUDO_OPTION="" bash setup.sh -s origin/master -x install;
    else
      ANSIBLE_SUDO_OPTION="" bash setup.sh -x install;
    fi

script:
  # setup.sh PATH update doesn't seem to work on Travis, add manually for now
  - ./travis.sh

after_success:
  - ./travis_pr_describe.sh || travis_terminate 1
  - ./publish.sh requirements.yaml || travis_terminate 1
  - PRODUCT_VERSION=v3 ./publish.sh build_v3_prod/piksi_firmware_v3_prod*.elf || travis_terminate 1
  # These tokens are in plaintext so Swift developers can make PR's from their
  # personal forks. We may want to revisit this at some point.
  - GITHUB_COMMENT_TOKEN=29ff16b8acbf635fad0c702d3189c04a997b9719 SLACK_CHANNEL=github ./comment.sh || travis_terminate 1
  - HITL_API_GITHUB_TOKEN=d70b53ef8e8e0966818c473c56c02bf45b17290b GITHUB_COMMENT_TOKEN=29ff16b8acbf635fad0c702d3189c04a997b9719 ./hitl_smoke_test.sh

env:
  global:
    # Secure keys below are encrypted with travis encrypt gem
    # Example encryption: travis encrypt AWS_SECRET_ACCESS_KEY=foo
    # See https://docs.travis-ci.com/user/encryption-keys/
    # AWS_ACCESS_KEY_ID
    - secure: "LsFsFWJH7rXV0jThali9EjPA3OZFjhhan3f/yn2Ant2NHY/7m4CEzlu2yHx3mynR63Xw2gMC+xWFOATCjST0pf9bIGAHFZYFz/RM9IG1/YcFd54I5tEcde7stJ5Pq/bS+au8WxiXAE7ythf9iOeEPIBr9WD6r3qCyrlSvMmjRL05yZ/3xUCIghuqy0Cg+j+beViOl678BTBvvsCqwQGi4M0nYyhV+wAIPaRXpNgJ5YjqTope+D5v2jP65pZwxamT6cwQYvy+PNL5yI+tphAvXiAhjauzQUl1H5lpdtQCu2py1HLfaKIeM4Nqi2pnOw6cZN84x4oSJ+tuzn9TqoyRrYG5lxzO/ZROu59NcjsFMS5mDSM51Nxc87Gc1GW6xLu4otYw4nKreVcZLFwHK+bA5wnaxuAexI4jTenEHaFxqsGxbuL+XQuRhwfyoV5y7+yCGfOIVoByVIxfC9HLtU/c73EsMA/e80ohIzw8LjrTdgCTAW5Ktx/oSS3jKtpFhTKd9UL73AXkbcPLsECR/60vvqCS0Bc/WkBJxCwO6v6Nl6vzdHoPPnjtjwFI01WYS2rlBVSQqyRVUDaovboDXyCggj+AJLU2kzVWWaAV8FYQx42AKleUn3BvtVINvX32QcBHh0xVxNAW6SXfUntoHVLl4bqcgb4FW8CBcKTXrM+2ANE="
    # AWS_SECRET_ACCESS_KEY
    - secure: "ey7p4qkpniFlhfcFgPTFpJMlAqKdtcUbQ1H9dfV5FUh8u30aplv5d8MrHbqQF7e5D6CEya9kkXNmAA+1ayS7uSfSmpueAOtaCvYA9iu7LgHDaSmGkHRSIfgpXGIqsNj2QzN3dKNd+ckfru89v0VUli7LFWDs7ZZxPjJsKJbLCD2QfsKyR4gh/uirAC7xvw20LveTssfhWByC/i6EjggGcNPrKGTbYTaot7o/ueIai9iH9wOznN2PTk+OgMnGbgO+wNbPsDAIjuDIVrd8SgC8YPiBpn9FeMZ0r5YnL+KjiTwRMV0y2Wi7gMDBv/p7B6ugtSeTj9h8Bfnikxyoze1ZCSV44q4djHBC/nj+86Tkv+5n96LzY2wMFxG46iDxStx3NRKTSr0DXzmWkgrWuJewzSa/3Vq0xla4nIoOCRNCV/XdylcJW3OtP9nCJAVOSqK3kniCTlgajK/B+LqwAcDACWpeNfcHEIAf7ZtUdyvo3ogFAnK8SSe8urHq5hBdHHyykrxXtqG9weKvCr4yPi+J+3rSzlr9P3XI59J5lVdxuv32XRWwz3rFhqPmRQ+l/q2fziQF0QyIIavuGg+rlASlY+gLP+EVkuESMByeR+yEmMuw7rPbaPuJMgqzD8Gxc/eG+35eIsk4S0YYZ53Uqlq/25n6UkNtCIwA4qKDV0Ck4ls="
    # SLACK_TOKEN
    - secure: "cNlOBL6qktZepCu+bwAQWczN1NAES3U/G+OYZ/vOAbj/oPJqXOESy0DqJQp63mZUaw1iCnTMl5wabeM0Xbbj7jfbyijSBKa2585jn6qIe0cwki3+F1PYJM1KMlu9P2QAoR8yF0JfLe8opWJXlbMXD+cEFiHX3ZIwXgM7k/OHK6Ovx3K53t3CsJQOhdELaxG5BgnLHt9sIwOvbgLLp1ksjzeZKrZl7c2ayraCXlL0fNbIg4yo6FHAvviQosflYxhR5AaymndSrW1rk+i8doFnRbWY7Yj3f6ZfN4woqXQEjMVMfLomK2a40jQgk7LMug4mPWVYLexK9WC+eUGwAb0X4rYdZRPMYX/YOIqAeil3HYDefhM1S95wCfwMEoCWRN/TO1PLxhg4xmM2Rb/zwJ5Pl9yclYSd1bpuvq7xByIGIfMcK+0sBoPqk4+R6N4LDNmSQ02udv1X2Mcvf3U17HcqGwdpZ7dBWyc3fZmr3VGDgPiclSghFL6hU0aLVrbdgkwZb7zfbK+5E2RK/Kd5gGpF2vGIxvDdt2G0J0u7VJA4EZ1ZMCLgHD+Dyb5/Ou9UdQfVCKH5LzN+O/qTIAJqWsadw0h4EQC091OgAHzRPOgIj/MFzow/AIZ0sBXAzsZ1/IsEklKgKov5u//63Y2RUHZLntSeK8Q/11FI9MBE/NXmSBE="
