sudo: required

os:
  - linux
  - osx

before-install:
  - pip install --user --upgrade awscli

install:
  - ANSIBLE_SUDO_OPTION="" bash setup.sh -x install
  - pip install boto3
  - pip install pyyaml

script:
  # setup.sh PATH update doesn't seem to work on Travis, add manually for now
  - export PATH=$PATH:~/gcc-arm-none-eabi/bin
  - make PIKSI_HW=v2
  - make clean
  - make PIKSI_HW=v3

after_success:
  - ./upload_artifacts.py

