version: '3.1'

services:
  piksi_firmware:
    build:
      context: .
      args:
        - UID=1000
    image: piksi_firmware
    volumes:
      - ${PWD}:/mnt/workspace:delegated
      - ${HOME}/.ssh/id_rsa:/home/jenkins/.ssh/id_rsa
      - ${HOME}/.ccache:/home/jenkins/.ccache:delegated
