---
-
  name: microzed
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_microzed.elf
        - piksi_firmware_v3_microzed.hex
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/3bc1822/v3/microzed/dev
      files:
        - boot.bin
        - u-boot.img
        - uImage.piksiv3_microzed
    -
      bucket: piksi-fpga-unlocked
      prefix: v3
      files:
        - piksi_microzed_fpga_v3.5_unlocked.bit
-
  name: evt1
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_evt1.elf
        - piksi_firmware_v3_evt1.hex
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/3bc1822/v3/evt1/dev
      files:
        - boot.bin
        - u-boot.img
        - uImage.piksiv3_evt1
    -
      bucket: piksi-fpga-unlocked
      prefix: v3
      files:
        - piksi_evt1_fpga_v3.5_unlocked.bit
-
  name: evt2
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_evt2.elf
        - piksi_firmware_v3_evt2.hex
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/3bc1822/v3/evt2/dev
      files:
        - boot.bin
        - u-boot.img
        - uImage.piksiv3_evt2
    -
      bucket: piksi-fpga-unlocked
      prefix: v3
      files:
        - piksi_evt2_fpga_v3.5-acq-test_unlocked.bit
