---
-
  name: microzed
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_microzed.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/v0.1-24-g2645cf0/v3/microzed
      files:
        - uImage.piksiv3_microzed
    -
      bucket: piksi-fpga-unlocked
      prefix: v3.7.1
      files:
        - piksi_microzed_fpga_unlocked.bit
-
  name: prod
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_prod.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/v0.1-32-g625bef0/v3/prod
      files:
        - uImage.piksiv3_prod
    -
      bucket: swiftnav-artifacts
      prefix: piksi_fpga/v3.7.1-wltr-test
      files:
        - piksi_prod_fpga.bit
