---
-
  name: prod
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_prod.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/v2.1.0-develop-2018111323/v3/prod
      files:
        - uImage.piksiv3_prod
    -
      bucket: swiftnav-artifacts-pull-requests
      prefix: piksi_fpga/v2.1.0-develop-2018111323-5-gc16ec8b
      files:
        - piksi_prod_fpga.bit
