---
-
  name: prod
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_prod.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot_private/v2.4.0-develop-2021102109/v3/prod
      files:
        - uImage.piksiv3_prod
    -
      bucket: swiftnav-artifacts
      prefix: piksi_fpga/v2.4.0-develop-2021102109
      files:
        - piksi_prod_fpga.bit
-
  name: base
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_base.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot_private/v2.4.0-develop-2021102109/v3/prod
      files:
        - uImage.piksiv3_prod
    -
      bucket: swiftnav-artifacts
      prefix: piksi_fpga/v2.4.0-develop-2021102109
      files:
        - piksi_base_fpga.bit