---
-
  name: prod
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_prod.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts-pull-requests
      prefix: piksi_buildroot/v1.5.15-9-gb67149a/v3/prod
      files:
        - uImage.piksiv3_prod
    -
      bucket: swiftnav-artifacts
      prefix: piksi_fpga/v1.5.0-develop-2018072323-1-g94280d2
      files:
        - piksi_prod_fpga.bit
