---
-
  name: prod
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_prod.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/v2.1.0-develop-2019030503/v3/prod
      files:
        - uImage.piksiv3_prod
    -
      bucket: swiftnav-artifacts
      prefix: piksi_fpga/v2.1.0-develop-2019030123-2-g13f7579
      files:
        - piksi_prod_fpga.bit