---
-
  name: microzed
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_microzed.elf
        - piksi_firmware_v3_microzed.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/8a17138/v3/microzed/dev
      files:
        - boot.bin
        - u-boot.img
        - uImage.piksiv3_microzed
    -
      bucket: piksi-fpga-unlocked
      prefix: v3.6.0
      files:
        - piksi_microzed_fpga_unlocked.bit
-
  name: evt2
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_evt2.elf
        - piksi_firmware_v3_evt2.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/8a17138/v3/evt2/dev
      files:
        - boot.bin
        - u-boot.img
        - uImage.piksiv3_evt2
    -
      bucket: piksi-fpga-unlocked
      prefix: v3.6.0
      files:
        - piksi_evt2_fpga_unlocked.bit
