---
-
  name: prod
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_prod.stripped.elf
  artifacts:
    -
      bucket: swiftnav-releases
      prefix: piksi_buildroot/v1.4.1/v3/prod
      files:
        - uImage.piksiv3_prod
    -
      bucket: swiftnav-releases
      prefix: piksi_fpga/v1.4.1
      files:
        - piksi_prod_fpga.bit