---
-
  name: prod
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_prod.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot_private/starling-v1.2.0-develop-2021030319/v3/prod
      files:
        - uImage.piksiv3_prod
    -
      bucket: swiftnav-artifacts
      prefix: piksi_fpga/starling-v1.2.0-develop-2021030319
      files:
        - piksi_prod_fpga.bit
-
  name: base
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_base.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot_private/starling-v1.2.0-develop-2021030319/v3/prod
      files:
        - uImage.piksiv3_prod
    -
      bucket: swiftnav-artifacts
      prefix: piksi_fpga/starling-v1.2.0-develop-2021030319
      files:
        - piksi_base_fpga.bit