---
-
  name: microzed
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_microzed.elf
        - piksi_firmware_v3_microzed.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/v0.1-14-gc7ba6ac/v3/microzed/dev
      files:
        - boot.bin
        - u-boot.img
        - uImage.piksiv3_microzed
    -
      bucket: piksi-fpga-unlocked
      prefix: v3.6.0
      files:
        - piksi_microzed_fpga_unlocked.bit
-
  name: prod
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_prod.elf
        - piksi_firmware_v3_prod.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/v0.1-14-gc7ba6ac/v3/prod/dev
      files:
        - boot.bin
        - u-boot.img
        - uImage.piksiv3_prod
    -
      bucket: swiftnav-artifacts
      prefix: piksi_fpga/v3.6.2
      files:
        - piksi_prod_fpga.bit
