---
-
  name: microzed
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_microzed.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/v4.0.0/v3/microzed
      files:
        - uImage.piksiv3_microzed
    -
      bucket: piksi-fpga-unlocked
      prefix: v3.6.0
      files:
        - piksi_microzed_fpga_unlocked.bit
-
  name: prod
  resources:
    -
      prefix: v3
      files:
        - piksi_firmware_v3_prod.stripped.elf
  artifacts:
    -
      bucket: swiftnav-artifacts
      prefix: piksi_buildroot/v4.0.0/v3/prod
      files:
        - uImage.piksiv3_prod
    -
      bucket: swiftnav-artifacts
      prefix: piksi_fpga/v4.0.0
      files:
        - piksi_prod_fpga.bit