/*
 * Copyright (C) 2019 Swift Navigation Inc.
 * Contact: Swift Navigation <dev@swiftnav.com>
 *
 * This source is subject to the license found in the file 'LICENSE' which must
 * be distributed together with this source. All other rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef LIBSWIFTNAV_PROCESS_NOISE_MOTION_H
#define LIBSWIFTNAV_PROCESS_NOISE_MOTION_H

typedef enum {
  HIGH_DYNAMICS = 0,
  HIGH_HORIZONTAL_DYNAMICS,
  LOW_DYNAMICS,
  MAX_PROCESS_NOISE_MOTION_TYPE
} PROCESS_NOISE_MOTION_TYPE;

#endif  // LIBSWIFTNAV_PROCESS_NOISE_MOTION_H
