##############################################################################
# Project, sources and paths
#

REVDIR := $(SWIFTNAV_ROOT)/src/board/v3/prod

REVINC := $(REVDIR)


REVASM :=

#
# Project, sources and paths
##############################################################################
