##############################################################################
# Project, sources and paths
#

REVDIR := $(SWIFTNAV_ROOT)/src/board/v3/prod

REVINC := $(REVDIR)

REVSRC := $(REVDIR)/board_rev.o

REVASM :=

#
# Project, sources and paths
##############################################################################
