/*
 * Copyright (C) 2016 - 2017 Swift Navigation Inc.
 * Contact: Michele Bavaro <michele@swiftnav.com>
 *
 * This source is subject to the license found in the file 'LICENSE' which must
 * be be distributed together with this source. All other rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef SWIFTNAV_PLATFORM_SIGNAL_H
#define SWIFTNAV_PLATFORM_SIGNAL_H

/* Platform-specific code support */
#define CODE_GPS_L1CA_SUPPORT 1
#define CODE_GPS_L2C_SUPPORT 1
#define CODE_GPS_L5_SUPPORT 1
#define CODE_GPS_AUX_SUPPORT 0
#define CODE_GLO_L1OF_SUPPORT 0
#define CODE_GLO_L2OF_SUPPORT 0
#define CODE_GPS_L1P_SUPPORT 1
#define CODE_GPS_L2P_SUPPORT 1
#define CODE_SBAS_L1CA_SUPPORT 1
#define CODE_QZSS_L1CA_SUPPORT 0
#define CODE_QZSS_L2C_SUPPORT 0
#define CODE_QZSS_L5_SUPPORT 0
#define CODE_BDS2_B1_SUPPORT 1
#define CODE_BDS2_B2_SUPPORT 1
#define CODE_BDS3_B5_SUPPORT 1
#define CODE_GAL_E1_SUPPORT 1
#define CODE_GAL_E5_SUPPORT 1
#define CODE_GAL_E7_SUPPORT 1

/* Tracker configuration */
#define NUM_TRACKER_CHANNELS MAX_CHANNELS

/* Decoder configuration */
#define NUM_DECODER_CHANNELS MAX_CHANNELS

#if defined CODE_GPS_L1CA_SUPPORT && CODE_GPS_L1CA_SUPPORT > 0
#define NUM_GPS_L1CA_DECODERS NAP_NUM_GPS_L1_CHANNELS
#else
#define NUM_GPS_L1CA_DECODERS 0
#endif /* CODE_GPS_L1CA_SUPPORT */

#if defined CODE_GPS_L2C_SUPPORT && CODE_GPS_L2C_SUPPORT > 0
#define NUM_GPS_L2C_DECODERS NAP_NUM_GPS_L2_CHANNELS
#else
#define NUM_GPS_L2C_DECODERS 0
#endif /* CODE_GPS_L2C_SUPPORT */

#if defined CODE_GPS_L5_SUPPORT && CODE_GPS_L5_SUPPORT > 0
#define NUM_GPS_L5_DECODERS NAP_NUM_GPS_L5_CHANNELS
#else
#define NUM_GPS_L5_DECODERS 0
#endif /* CODE_GPS_L5_SUPPORT */

#if defined CODE_GLO_L1OF_SUPPORT && CODE_GLO_L1OF_SUPPORT > 0
#define NUM_GLO_L1OF_DECODERS NAP_NUM_GLO_G1_CHANNELS
#else
#define NUM_GLO_L1OF_DECODERS 0
#endif /* CODE_GLO_L1OF_SUPPORT */

#if defined CODE_GLO_L2OF_SUPPORT && CODE_GLO_L2OF_SUPPORT > 0
#define NUM_GLO_L2OF_DECODERS NAP_NUM_GLO_G2_CHANNELS
#else
#define NUM_GLO_L2OF_DECODERS 0
#endif /* CODE_GLO_L2OF_SUPPORT */

#if defined CODE_BDS2_B1_SUPPORT && CODE_BDS2_B1_SUPPORT > 0
#define NUM_BDS2_B11_DECODERS NAP_NUM_BDS_B1_CHANNELS
#else
#define NUM_BDS2_B11_DECODERS 0
#endif /* CODE_BDS2_B1_SUPPORT */

#if defined CODE_BDS2_B2_SUPPORT && CODE_BDS2_B2_SUPPORT > 0
#define NUM_BDS2_B2_DECODERS NAP_NUM_BDS_B2_CHANNELS
#else
#define NUM_BDS2_B2_DECODERS 0
#endif /* CODE_BDS2_B2_SUPPORT */

#if defined CODE_BDS3_B5_SUPPORT && CODE_BDS3_B5_SUPPORT > 0
#define NUM_BDS3_B5_DECODERS NAP_NUM_BDS_L5_CHANNELS
#else
#define NUM_BDS3_B5_DECODERS 0
#endif /* CODE_BDS3_B5_SUPPORT */

#if defined CODE_QZSS_L1CA_SUPPORT && CODE_QZSS_L1CA_SUPPORT > 0
#define NUM_QZSS_L1CA_DECODERS NAP_NUM_GPS_L1_CHANNELS
#else
#define NUM_QZSS_L1CA_DECODERS 0
#endif /* CODE_QZSS_L1CA_SUPPORT */

#if defined CODE_QZSS_L2C_SUPPORT && CODE_QZSS_L2C_SUPPORT > 0
#define NUM_QZSS_L2C_DECODERS NAP_NUM_GPS_L2_CHANNELS
#else
#define NUM_QZSS_L2C_DECODERS 0
#endif /* CODE_QZSS_L2C_SUPPORT */

#if defined CODE_QZSS_L5_SUPPORT && CODE_QZSS_L5_SUPPORT > 0
#define NUM_QZSS_L5_DECODERS NAP_NUM_GPS_L5_CHANNELS
#else
#define NUM_QZSS_L5_DECODERS 0
#endif /* CODE_QZSS_L5_SUPPORT */

#if defined CODE_SBAS_L1CA_SUPPORT && CODE_SBAS_L1CA_SUPPORT > 0
#define NUM_SBAS_L1_DECODERS NAP_NUM_SBAS_L1_CHANNELS
#else
#define NUM_SBAS_L1_DECODERS 0
#endif /* CODE_SBAS_L1CA_SUPPORT */

#if defined CODE_GAL_E1_SUPPORT && CODE_GAL_E1_SUPPORT > 0
#define NUM_GAL_E1_DECODERS NAP_NUM_GAL_E1_CHANNELS
#else
#define NUM_GAL_E1_DECODERS 0
#endif /* CODE_GAL_E1_SUPPORT */

#if defined CODE_GAL_E7_SUPPORT && CODE_GAL_E7_SUPPORT > 0
#define NUM_GAL_E7_DECODERS NAP_NUM_GAL_E7_CHANNELS
#else
#define NUM_GAL_E7_DECODERS 0
#endif /* CODE_GAL_E7_SUPPORT */

#if defined CODE_GAL_E5_SUPPORT && CODE_GAL_E5_SUPPORT > 0
#define NUM_GAL_E5_DECODERS NAP_NUM_GAL_E5_CHANNELS
#else
#define NUM_GAL_E5_DECODERS 0
#endif /* CODE_GAL_E5_SUPPORT */

void platform_track_setup(void);
void platform_decode_setup(void);

void platform_ndb_init(void);
void platform_ndb_sbp_updates(void);

#endif /* SWIFTNAV_PLATFORM_SIGNAL_H */
