/*
 * Copyright (C) 2016 - 2017 Swift Navigation Inc.
 * Contact: Michele Bavaro <michele@swiftnav.com>
 *
 * This source is subject to the license found in the file 'LICENSE' which must
 * be be distributed together with this source. All other rights reserved.
 *
 * THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
 * EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef SWIFTNAV_PLATFORM_SIGNAL_H
#define SWIFTNAV_PLATFORM_SIGNAL_H

/* Platform-specific code support */
#define CODE_GPS_L1CA_SUPPORT 1
#define CODE_GPS_L2CM_SUPPORT 1
#define CODE_GPS_L2CL_SUPPORT 1
#define CODE_SBAS_L1CA_SUPPORT 0
#define CODE_GLO_L1OF_SUPPORT 1
#define CODE_GLO_L2OF_SUPPORT 1
#define CODE_BDS2_B11_SUPPORT 1
#define CODE_BDS2_B2_SUPPORT 0
#define CODE_GPS_L1P_SUPPORT 1
#define CODE_GPS_L2P_SUPPORT 1

/* Tracker configuration */
#define NUM_TRACKER_CHANNELS MAX_CHANNELS
#define NUM_GPS_L1CA_TRACKERS NAP_NUM_GPS_L1_CHANNELS
#define NUM_GPS_L2CM_TRACKERS NAP_NUM_GPS_L2_CHANNELS
#define NUM_GPS_L2CL_TRACKERS NAP_NUM_GPS_L2_CHANNELS
#define NUM_GLO_L1OF_TRACKERS NAP_NUM_GLO_G1_CHANNELS
#define NUM_GLO_L2OF_TRACKERS NAP_NUM_GLO_G2_CHANNELS
#define NUM_BDS2_B11_TRACKERS NAP_NUM_BDS_B1_CHANNELS
#define NUM_BDS2_B2_TRACKERS  NAP_NUM_BDS_B2_CHANNELS

/* Decoder configuration */
#define NUM_DECODER_CHANNELS MAX_CHANNELS
#define NUM_GPS_L1CA_DECODERS NAP_NUM_GPS_L1_CHANNELS
#define NUM_GPS_L2CM_DECODERS NAP_NUM_GPS_L2_CHANNELS
#define NUM_GLO_L1OF_DECODERS NAP_NUM_GLO_G1_CHANNELS
#define NUM_GLO_L2OF_DECODERS NAP_NUM_GLO_G2_CHANNELS
#define NUM_BDS2_B11_DECODERS NAP_NUM_BDS_B1_CHANNELS
#define NUM_BDS2_B2_ DECODERS NAP_NUM_BDS_B2_CHANNELS

void platform_track_setup(void);
void platform_decode_setup(void);

void platform_ndb_init(void);
void platform_ndb_sbp_updates(void);

#endif /* SWIFTNAV_PLATFORM_SIGNAL_H */
