##############################################################################
# Project, sources and paths
#

REVDIR := $(SWIFTNAV_ROOT)/src/board/v3/microzed

REVINC := $(REVDIR)

REVSRC := $(REVDIR)/board.o

REVASM :=

#
# Project, sources and paths
##############################################################################
