##############################################################################
# Project, sources and paths
#

REVDIR := $(SWIFTNAV_ROOT)/src/board/v3/base

REVINC := $(REVDIR)

REVSRC :=

REVASM :=

#
# Project, sources and paths
##############################################################################
