# Install arm-gcc tools via:
# https://launchpad.net/~terry.guo/+archive/ubuntu/gcc-arm-embedded

- name: Add ARM GCC repo toolchain repository
  apt_repository:
    repo: ppa:team-gcc-arm-embedded/ppa
    state: present
  become: true
  become_method: sudo

- name: Updating apt-cache
  apt: update_cache=yes
  become: true
  become_method: sudo

- name: Install ARM GCC toolchain (all Ubuntu distributions)
  apt: pkg={{ item }} state=latest
  with_items:
    - gcc-arm-embedded
  become: true
  become_method: sudo

# If arm-gcc installation does not succeed, register failture and
# install manually with next role.
- name: Checking for arm gcc again.
  shell: which arm-none-eabi-gcc 2>&1 1>/dev/null && echo y || echo n
  register: armgcc_manual
