# Install arm-gcc tools via:
# https://launchpad.net/~terry.guo/+archive/ubuntu/gcc-arm-embedded

- name: Add ARM GCC repo toolchain repository
  sudo: True
  command: add-apt-repository -y ppa:team-gcc-arm-embedded/ppa

- name: Updating apt-cache
  sudo: True
  apt: update_cache=yes

- name: Install ARM GCC toolchain (all Ubuntu distributions)
  apt: pkg={{ item }} state=latest
  sudo: True
  ignore_errors: True
  with_items:
    - gcc-arm-embedded

# If arm-gcc installation does not succeed, register failture and
# install manually with next role.
- name: Checking for arm gcc again.
  shell: which arm-none-eabi-gcc
  register: armgcc_manual
  ignore_errors: True
