# Download and install arm-gcc compiler and add to path. This doesn't
# run if already have it: i.e., if gcc-arm-none is already in your
# PATH after sys_deps.yml.
#
# Currently hardcoded to use the GNU ARM embedded toolchain, version 6-q2.

- file: state=directory path=~/gcc-arm-none-eabi

- name: Download and unpack gcc-arm utilities.
  unarchive:
    src: https://github.com/swift-nav/swift-toolchains/releases/download/pfwp/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
    remote_src: yes
    dest: ~/gcc-arm-none-eabi
    extra_opts: '--strip-components=1'

- name: Check bash profile.
  stat: path=~/.bash_profile
  register: bash_profile_present

- name: Check for ~/.profile
  stat: path=~/.profile
  register: dot_profile_present

- name: Add arm-gcc directory to PATH (~/.bash_profile)
  when: bash_profile_present.stat.exists and not dot_profile_present.stat.exists
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH=$PATH:$HOME/gcc-arm-none-eabi/bin'

- name: Add arm-gcc directory to PATH (~/.profile)
  when: not bash_profile_present.stat.exists and dot_profile_present.stat.exists
  lineinfile:
    path: ~/.profile
    line: 'export PATH=$PATH:$HOME/gcc-arm-none-eabi/bin'
