- include: sys_deps.yml

# Install arm if it doesn't exist.
- name: Attempting to install ARM GCC with Apt
  include: arm.yml
  when: force_manual_gcc != "y" and armgcc.stdout != "y"

# If arm-gcc installation does not succeed, register failture and
# install manually with next role.
- name: Checking for arm gcc again.
  shell: which arm-none-eabi-gcc 2>&1 1>/dev/null && echo y || echo n
  register: armgcc_manual

# If apt-get install for arm fails, install manually.
- name: Manually installing ARM GCC
  include: arm_manual.yml
  when: (force_manual_gcc == "y" and armgcc_manual.stdout != "y") or (armgcc.stdout != "y" and armgcc_manual.stdout != "y")
